### ISSUE TITLE
Back-end signup, login, reset password, forgot password overview.

### ISSUE THREAD

**Issue by ArnasDickus** [zero-to-mastery/mappypals_backend#9]
So after approving [PR #8](https://github.com/zero-to-mastery/mappypals_backend/pull/8) I think it's time to answer important questions and talk about the mappypals future back-end. Here I'm going to talk about our login, reset password, forgot password, current state.

<strong>How do you work on the back-end?</strong>
1) Using [this instruction](https://github.com/zero-to-mastery/mappypals/blob/master/pr-guide.pdf) fork mappypals front-end and mappypals back-end. To launch:
   1.1)  mappypals: in cmd write `npm install` and `npm start`
   1.2) mappypals back-end in cmd write `npm install`, create a new file .env and put content of env example file into newly created .env file. Run `npm start`

 <strong>How to sign up to mappypals, using signup form? Currently, it doesn't actually work</strong>
1) To signup use fake email services for [example](https://ethereal.email/) Click create an Etheral account.
2) Make sure you have running [mappypals](https://github.com/zero-to-mastery/mappypals) and [mappypals_back-end](https://github.com/zero-to-mastery/mappypals_backend)
3) On signup form enter information, 
     3.1) FirstName, and Lastname can be random. 
     3.2) Make sure you entered the provided email from Etheral. Do not close Etheral email window
     3.3) Due to the front-end validation provided password is too weak. So use this password instead of `Agenericpass1!` 
4) Sometimes you get an error Enter all fields in mappypals_back-end cmd. If that happens comment it out signup.js everything below clear inputs. That happens possibly because of async.
5) After you registered successfully. From cmd copy preview URL and visit that link.
![back-end-register](https://user-images.githubusercontent.com/38657595/59920971-ed2efa80-9434-11e9-8d4b-6b0455133cc2.jpg)
6) Click on the email link to get redirected to the login page.
7) Trying to login will give you an unauthorized error. 
  7.1) Get MongoDB credentials, they are in mappypals discord pinned messages.
 7.2) Login click on collections.
 7.3) Find your account manually change active from false to true.
 7.4) Now trying to login will give you internal server error.

<strong>How to Reset Password?</strong>
1) on the login page, click on the forgot password.
2) Enter email, click submit.
![reset-password](https://user-images.githubusercontent.com/38657595/59920960-e4d6bf80-9434-11e9-8e8a-9a5881f4f201.jpg)
3) Click on the provided link. you will get taken to email, click on the email link. Get redirected to reset the password.
4) Trying to reset password does not work. You entered information but nothing happens and the password is the same.

<strong>So here are my concerns:</strong>
1) Signup.js set state reset forms interferes with the async function. And a result can give an error that fields are empty.
2) Signup.js after registration does not redirect the user to the login page.
3) After signing up clicking on the provided link does not change active from false to true.
4) Trying to signup with MongoDB account gives you an internal error.
5) Reseting password requires only an email. You get a link on a website instead of your email box. 
6) Need to add redux state so that on login both home.js page and navbar would change appropriately
7) Reset password does not actually reset the password, and does not redirect the user to the home page.

Anyways since I'm not a back-ender I might have missed something so let me know your thoughts.

**Comment by ArnasDickus** [comment]
So to fully fix this issue, here's my proposed tasks:
1) Improve login forms
   1.1) Remove signup setState from forms, or add a timer to it so that it won't interfere with async functions. To avoid Enter all fields error.
   1.2) Add redirection to home page after, successful login.

2) Database active change
  2.1) After signing up, clicking on send a link, in MongoDB account should change active from false to true.

3) Allow to sign up.
  3.1) Signing up should redirect the user to the dashboard.
  3.2) Using redux, make sure that logged in accounts only see the dashboard and logged in the navbar. And vice versa.

4) Reset password.
 4.1) Reset password should reset password
 4.2) A link should be sent to email and not appear on the website, forgot password form.

So let me know your thoughts about this?

**Comment by nottoobright** [comment]
I mostly agree with all the points, just one little correction. To signup, one does not need to signup an account for Etheral, the to and from emails don't matter at all right now as long as they are not blank. We can fix that up in future tasks when our website is live as well.

**Comment by ArnasDickus** [comment]
Hello, @nottoobright need some clarification, So yes you don't need signup using Ethereal, You can create any email, and in Mongo DB change the active status to true. Ethereal is for mimicking the process with real emails. However, it doesn't fully work because you can't activate the account in step 5. Is my understanding correct?

regarding `the to and from emails don't matter at all right now as long as they are not blank`. there is front-end validation helper function [IsPasswordValid](https://github.com/zero-to-mastery/mappypals/blob/dev/src/components/helper.js). So you can't in email input add random text. Are you talking here about back-end validation?

**Comment by ArnasDickus** [comment]
I feel like I'm over my head with this overview, as a result, I can't create precise Trello tasks, for everyone to understand. So I decided to look through it and analyze again:

Signup.js What do we have/need
1) Mockup <strong>completed</strong>
2) Front-end email validation, password validation <strong>completed</strong>
2) Filled details are sent to the database <strong>completed</strong>
3) The user gets redirected to the login page,  <strong>completed</strong>
4) Fixed clear forms bug with async interferences <strong>completed</strong>
5) Display an error if the user email is already registered on the website <strong>completed</strong>
6) Clicking on the signup link, the account becomes active. [Task](https://trello.com/c/2Go8gu0j/164-email-user-activation-signupjs)
7) Back-end validation not completed. [Task added](https://trello.com/c/0Zq0adgU/144-sign-up-validation)
8) User get's informed that email has been verified.

Login.js
1) Mockup <strong>completed</strong>
2) Check if account is active,  <strong>completed</strong>
3) If account active: false he can still login. [login task](https://trello.com/c/0PGQBvQG/166-allow-user-to-login-loginjs)
4) Bug, trying to login with correct info gives you Internal Server Error. [login task](https://trello.com/c/0PGQBvQG/166-allow-user-to-login-loginjs)
![internal-server-errror](https://user-images.githubusercontent.com/38657595/59976280-c0145080-95ca-11e9-91e1-f9bf41e0ba21.jpg)
5) redux state for login users [Trello task](https://trello.com/c/Evcrlbr2/162-redux-state-for-login-waiting-for-improve-signup-form) not Implemented

ForgotPassword.js
1) Mockup <strong>completed</strong>
2) Do not display Etheral link on Forgot Password.js. <strong>completed</strong>
ResetPassword.js
1) Mockup <strong>completed</strong>
2) Reset passwords resets paswords [task added](https://trello.com/c/01lN84sF/163-reset-password-resetpasswordjs-forgotpasswordjs)

According to @mubarakshow:
So the way email verification works on many top apps and website I've used is this:
1. User sign up
2. The user gets informed that an email verification link has been sent to their email box
3. The user gets redirected to the login 
4. User can log in
5.  In the user profile, under email, 
- if the user has verified their email, there's a green verified tag 
- if the email has not been verified, there's a red unverified tag with a resend verification email button underneath
That's the ideal flow of user authentication

**Comment by ArnasDickus** [comment]
Closing this due to being outdated.
